twitter_description: A landing page for all in-person training sessions hold by Florian Dahlitz. The idea is to provide participants a single page to access the courses resources.
twitter_image_url: twitter_thumbnail.jpg
twitter_title: Training - Florian Dahlitz
twitter_url: https://training.florian-dahlitz.de